services:
  postgres:
    image: postgres:15
    container_name: post_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postdb
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5433" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========== REDIS ==========
  redis:
    image: redis:7-alpine
    container_name: post_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
  # ===========================

volumes:
  postgres_data:
  redis_data:
