CREATE TABLE IF NOT EXISTS posts (
     id BIGSERIAL PRIMARY KEY,
     author_id BIGINT NOT NULL,
     title VARCHAR(200) NOT NULL,   
     content TEXT NOT NULL,
     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);